# Use the official Go image as the base image
FROM golang:latest AS build
# Set the working directory inside the container
WORKDIR /app
# Copy the Go modules files
COPY go.mod go.sum ./
# Download and install Go dependencies
RUN go mod download
# Copy the rest of the application code
COPY . .
# Build the Go application
RUN go build -o main .
# Expose port 9090
EXPOSE 9090
# Command to run the Go application
CMD ["./main"]
